---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver on ubuntu ansible nodes side
    apt:
      name: apache2 
      state: present
    when: ansible_os_family=="Debian"

  - name: start webserver on ubuntu ansible nodes side
    service: 
      name: apache2
      state: started
    when: ansible_os_family=="Debian"


